In [22]:
#Studied BAG-OF-WORDS(BOW) IN NLP

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('IMDB Dataset.csv')

In [7]:
df.sample(5)

review sentiment
27701  If there were a movie that deserved a 0 out of...  negative
23525  Cimarron was painful to sit through. Although ...  negative
31685  This is very dated, but that's part of the cha...  positive
47233  This is a terrible movie, terrible script, bad...  negative
18674  My Caddy Limo was destroyed!!! Well, I had one...  negative

In [9]:
df.shape

(50000, 2)

In [11]:
df = pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'],'output':[1,1,0,0]})

In [12]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [19]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [21]:
cv.transform(["campusx watch and  write comment  of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])